name: Sync Fork with Upstream

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/mack-a/v2ray-agent.git
          git fetch upstream

      - name: Sync with upstream
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout master || git checkout main || git checkout master
          git merge upstream/master --no-edit || git merge upstream/main --no-edit || git merge upstream/master --no-edit
          git push origin HEAD
